# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be5866f340a252d255ad91bb6f2e9ea88d6447685796bce57953b4be640c3288e5d19a29211266252240ae91b54040c046af7c58d27640bcc56e86aa43df1a9e

test:
  secret_key_base: 43ee9ded69cf3cb3fac13c3bcdae371ca9e4502dec99cd2548f04777fc545f95b3fd4e99c0afdabf26f23599e81e14db1cfd219cbc25a4cdec3633a66124899f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
